### ISSUE TITLE
Setup repo good practices/templates

### ISSUE THREAD

**Issue by jake-mok-nelson** [JasonThomasData/ausGovWebCrawler#5]
## What
Configure some repo good practices/templates

## Why
Normally this is done when you initialise a new repository to get the team working consistently.

## How
In my opinion, the basic things I'd setup for a new repo are:
- Add editorconfig file to the repo & add the corresponding extension to the dev container - this gets devs on the same page around formatting.
- .gitignore - this helps us ignore certain file types from accidental commits to the repository and helps maintain repository hygiene. 
- pull_request_template - helps identify the things we expect people to do when contributing code and helps us easily identify the goal of a pull request.
- issue templates
  - feature
  - bug
- CODEOWNERS - helps us maintain ownership of the project for easy code reviews in the event others want to contribute.

## Definition of done

Good practices that are agreed during grooming to add value should be added.

**Comment by JasonThomasData** [comment]
We're leaving CODEOWNERS out for now
